name: TheWalls
version: '${project.version}'
main: ca.thewalls.TheWalls
api-version: 1.19
authors: [ CKAY9 ]
description: Play The Walls in any Minecraft world
commands:
  wstart:
    description: Start a new game of The Walls
  wend:
    description: End the ongoing game of The Walls
  wforceteam:
    description: Switch/Respawn a player to a team
  wleaderboard:
    description: Get the top 5 best players
  wevents:
    description: Get the active events for The Walls